version: "0.1"
services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./:/server
      - ./docker_stuff/site.conf:/etc/nginx/conf.d/default.conf
    links:
    - php-fpm
    - db
  php-fpm:
    build: "."
    dockerfile: ./docker_stuff/php-fpm.dockerfile
    volumes:
      - ./:/server
    links:
      - db
  db:
    build: "."
    dockerfile: ./docker_stuff/postgres.dockerfile
    environment:
      - POSTGRES_PASSWORD=dnd
      - POSTGRES_USER=postgres
      - POSTGRES_DB=dnd